-- Contract step: drop the per-rule on/off switch the AI invented and the human removed
-- (NOTES 2.23). Tenant configuration is the rule order only, as the brief asks.
-- Generated by drizzle-kit from src/infrastructure/db/schema.
--
-- Live-safe: the previous release already stopped reading the column (expand/contract), DROP
-- COLUMN changes the catalogue only and rewrites no rows, and the runner's lock_timeout bounds
-- the brief ACCESS EXCLUSIVE lock. tenant_rule_config has no rows and no API.
-- Rollback: ALTER TABLE tenant_rule_config ADD COLUMN enabled BOOLEAN NOT NULL DEFAULT TRUE.
ALTER TABLE "tenant_rule_config" DROP COLUMN "enabled";
